/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package super_puissance_4;

/**
 *
 * @author Legier
 */
public class fenetreDeJeu extends javax.swing.JFrame {

    Joueur[] ListeJoueurs = new Joueur[2];
    //Joueur joueur;
    Grille grilleDeJeu = new Grille();
    Joueur joueurCourant;

    /**
     * Creates new form fenetreDeJeu
     */
    public fenetreDeJeu() {
        initComponents();
        PanneauInfoPartie.setVisible(false);
        PanneauInfoJeu.setVisible(false);

        for (int i = 5; i >= 0; i--) {
            for (int j = 0; j < 7; j++) {
                CelluleGraphique cellGraph = new CelluleGraphique(grilleDeJeu.CellulesJeu[i][j]);

                cellGraph.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {

                        Cellule c = cellGraph.celluleAssociee;
                        
                       
                        
                        if (c.jetonCourant == null) {
                            return;
                        }

                        if (c.jetonCourant.Couleur.equals(joueurCourant.Couleur)) {
                            message.setText("le joueur" + joueurCourant.Nom + " récupère un de ses jetons");
                            c.supprimerJeton();
//Jeton jrecup = c.recupererJeton();
                            Jeton jrecup = c.recupererJeton() ;
                            joueurCourant.ajouterJeton(jrecup);
                            joueurSuivant();

                        } else {
                            if (joueurCourant.nombreDesintegrateurs > 0) {
                                message.setText("le joueur " + joueurCourant.Nom + " veut désintégrer un jeu");
                                c.supprimerJeton();
                                joueurCourant.utiliserDesintegrateur();
                                joueurSuivant();

                            } else {
                                return;
                            }

                        }
                        grilleDeJeu.tasserGrille();
                        PanneauGrille.repaint();
                        
                        nbdesintJoueur1.setText(ListeJoueurs[0].nombreDesintegrateurs + "");
                        nbdesintJoueur2.setText(ListeJoueurs[1].nombreDesintegrateurs + "");

                        boolean v1 = grilleDeJeu.etreGagnantPourJoueur(ListeJoueurs[0]);
                        boolean v2 = grilleDeJeu.etreGagnantPourJoueur(ListeJoueurs[1]);

                        if (v1 && !v2) {
                            message.setText("Victoire de" + ListeJoueurs[0].Nom);
                        }
                        if (v2 && !v1) {
                            message.setText("Victoire de" + ListeJoueurs[1].Nom);
                        }

                        if (v1 && v2) {
                            if (joueurCourant == ListeJoueurs[0]) {
                                message.setText("Victoire de" + ListeJoueurs[1].Nom + "(faute de jeu de l'adversaire");
                            } else {
                                message.setText("Victoire de" + ListeJoueurs[0].Nom + "(faute de jeu de l'adversaire");
                            }
                        }

                    }
                });

                PanneauGrille.add(cellGraph);

            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanneauInfoPartie = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nomJoueur1 = new javax.swing.JLabel();
        couleurJoueur1 = new javax.swing.JLabel();
        nbdesintJoueur1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        nomJoueur2 = new javax.swing.JLabel();
        couleurJoueur2 = new javax.swing.JLabel();
        nbdesintJoueur2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        PanneauInfoJoueur = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nom1 = new javax.swing.JTextField();
        nom2 = new javax.swing.JTextField();
        start = new javax.swing.JButton();
        PanneauInfoJeu = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        joueur = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        message = new javax.swing.JTextArea();
        PanneauGrille = new javax.swing.JPanel();
        col0 = new javax.swing.JButton();
        col1 = new javax.swing.JButton();
        col2 = new javax.swing.JButton();
        col3 = new javax.swing.JButton();
        col4 = new javax.swing.JButton();
        col5 = new javax.swing.JButton();
        col6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1060, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanneauInfoPartie.setBackground(new java.awt.Color(51, 255, 204));
        PanneauInfoPartie.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel3.setText("Infos Joueurs :");
        PanneauInfoPartie.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Joueur 1 :");
        PanneauInfoPartie.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 34, -1, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("- couleur :");
        PanneauInfoPartie.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 54, -1, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("- desintégrateur :");
        PanneauInfoPartie.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 74, 120, 20));

        nomJoueur1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nomJoueur1.setText("nom1");
        PanneauInfoPartie.add(nomJoueur1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 34, -1, 20));

        couleurJoueur1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        couleurJoueur1.setText("couleur1");
        PanneauInfoPartie.add(couleurJoueur1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 54, -1, 20));

        nbdesintJoueur1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nbdesintJoueur1.setText("nbdesint1");
        PanneauInfoPartie.add(nbdesintJoueur1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 74, -1, 20));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Joueur 2 :");
        PanneauInfoPartie.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("- couleur :");
        PanneauInfoPartie.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("- desintégrateur :");
        PanneauInfoPartie.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 120, -1));

        nomJoueur2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nomJoueur2.setText("nom2");
        PanneauInfoPartie.add(nomJoueur2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, -1, -1));

        couleurJoueur2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        couleurJoueur2.setText("couleur2");
        PanneauInfoPartie.add(couleurJoueur2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, -1));

        nbdesintJoueur2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nbdesintJoueur2.setText("nbdesint2");
        PanneauInfoPartie.add(nbdesintJoueur2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        PanneauInfoPartie.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 330, 10));

        getContentPane().add(PanneauInfoPartie, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 250, 350, 180));

        PanneauInfoJoueur.setBackground(new java.awt.Color(0, 204, 204));
        PanneauInfoJoueur.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        PanneauInfoJoueur.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel1.setText("Joueur 2 :");
        PanneauInfoJoueur.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 76, 70, 30));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel2.setText("Joueur 1 :");
        PanneauInfoJoueur.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 70, 30));

        nom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nom1ActionPerformed(evt);
            }
        });
        PanneauInfoJoueur.add(nom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 110, 30));
        PanneauInfoJoueur.add(nom2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 110, 30));

        start.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        start.setText("Démarrer partie");
        start.setName(""); // NOI18N
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });
        PanneauInfoJoueur.add(start, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 133, 180, 30));

        getContentPane().add(PanneauInfoJoueur, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 60, 350, 180));

        PanneauInfoJeu.setBackground(new java.awt.Color(0, 204, 204));
        PanneauInfoJeu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel7.setText("Infos Jeu :");
        PanneauInfoJeu.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Joueur courant :");
        PanneauInfoJeu.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 34, -1, 20));

        joueur.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        joueur.setText("nomJoueur");
        PanneauInfoJeu.add(joueur, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 34, -1, 20));

        message.setColumns(20);
        message.setRows(5);
        jScrollPane1.setViewportView(message);

        PanneauInfoJeu.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 300, 110));

        getContentPane().add(PanneauInfoJeu, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 440, 350, 190));

        PanneauGrille.setBackground(new java.awt.Color(255, 255, 255));
        PanneauGrille.setLayout(new java.awt.GridLayout(6, 7));
        getContentPane().add(PanneauGrille, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 672, 576));

        col0.setText("1");
        col0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                col0ActionPerformed(evt);
            }
        });
        getContentPane().add(col0, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        col1.setText("2");
        col1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                col1ActionPerformed(evt);
            }
        });
        getContentPane().add(col1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        col2.setText("3");
        col2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                col2ActionPerformed(evt);
            }
        });
        getContentPane().add(col2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        col3.setText("4");
        col3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                col3ActionPerformed(evt);
            }
        });
        getContentPane().add(col3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, -1));

        col4.setText("5");
        col4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                col4ActionPerformed(evt);
            }
        });
        getContentPane().add(col4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, -1, -1));

        col5.setText("6");
        col5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                col5ActionPerformed(evt);
            }
        });
        getContentPane().add(col5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, -1, -1));

        col6.setText("7");
        col6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                col6ActionPerformed(evt);
            }
        });
        getContentPane().add(col6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, -1, -1));

        setBounds(0, 0, 1085, 800);
    }// </editor-fold>//GEN-END:initComponents

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        PanneauInfoPartie.setVisible(true);
        PanneauInfoJeu.setVisible(true);
        initialiserPartie();
        PanneauGrille.repaint();
        start.setEnabled(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_startActionPerformed

    private void nom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nom1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nom1ActionPerformed

    private void col2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_col2ActionPerformed
        // TODO add your handling code here:

        jouerDansColonne(3);
        if (grilleDeJeu.colonneRemplie(3) == true) {
            col2.setEnabled(false);
        }
        joueurSuivant();
    }//GEN-LAST:event_col2ActionPerformed

    private void col6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_col6ActionPerformed
        // TODO add your handling code here:

        jouerDansColonne(7);
        if (grilleDeJeu.colonneRemplie(7) == true) {
            col6.setEnabled(false);
        }
        joueurSuivant();
    }//GEN-LAST:event_col6ActionPerformed

    private void col0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_col0ActionPerformed
        // TODO add your handling code here:

        jouerDansColonne(1);
        if (grilleDeJeu.colonneRemplie(1) == true) {
            col0.setEnabled(false);
        }
        joueurSuivant();
    }//GEN-LAST:event_col0ActionPerformed

    private void col1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_col1ActionPerformed
        // TODO add your handling code here:

        jouerDansColonne(2);
        if (grilleDeJeu.colonneRemplie(2) == true) {
            col1.setEnabled(false);
        }
        joueurSuivant();
    }//GEN-LAST:event_col1ActionPerformed

    private void col3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_col3ActionPerformed
        // TODO add your handling code here:

        jouerDansColonne(4);
        if (grilleDeJeu.colonneRemplie(4) == true) {
            col3.setEnabled(false);
        }
        joueurSuivant();
    }//GEN-LAST:event_col3ActionPerformed

    private void col4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_col4ActionPerformed
        // TODO add yjouerDansColonne(5);our handling code here:

        jouerDansColonne(5);
        if (grilleDeJeu.colonneRemplie(5) == true) {
            col4.setEnabled(false);
        }
        joueurSuivant();
    }//GEN-LAST:event_col4ActionPerformed

    private void col5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_col5ActionPerformed
        // TODO add your handling code here:
        jouerDansColonne(6);
        if (grilleDeJeu.colonneRemplie(6) == true) {
            col5.setEnabled(false);
        }
        joueurSuivant();

    }//GEN-LAST:event_col5ActionPerformed

    public boolean jouerDansColonne(int indice_colonne) {

        boolean resultatAction = grilleDeJeu.ajouterJetonDansColonne(joueurCourant, indice_colonne);
        PanneauGrille.repaint();
        
        
            
  

        nbdesintJoueur1.setText(ListeJoueurs[0].nombreDesintegrateurs + "");
        nbdesintJoueur2.setText(ListeJoueurs[1].nombreDesintegrateurs + "");

        boolean v1 = grilleDeJeu.etreGagnantPourJoueur(ListeJoueurs[0]);
        boolean v2 = grilleDeJeu.etreGagnantPourJoueur(ListeJoueurs[1]);

        if (v1 && !v2) {
            message.setText("Victoire de" + ListeJoueurs[0].Nom);
        }
        if (v2 && !v1) {
            message.setText("Victoire de" + ListeJoueurs[1].Nom);
        }

        if (v1 && v2) {
            if (joueurCourant == ListeJoueurs[0]) {
                message.setText("Victoire de" + ListeJoueurs[1].Nom + "(faute de jeu de l'adversaire");
            } else {
                message.setText("Victoire de" + ListeJoueurs[0].Nom + "(faute de jeu de l'adversaire");
            }
        }

        if (resultatAction == true) {
            return true;
        } else {
            return false;
        }

    }

    public void joueurSuivant() {
        if (joueurCourant == ListeJoueurs[0]) {
            joueurCourant = ListeJoueurs[1];
           
        } else {
            joueurCourant = ListeJoueurs[0];

        }
        joueur.setText(joueurCourant.Nom);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fenetreDeJeu().setVisible(true);
            }
        });
    }

    public void initialiserPartie() {

        grilleDeJeu.viderGrille();

        String nomJ1 = nom1.getText();
        Joueur J1 = new Joueur(nomJ1);

        ListeJoueurs[0] = J1;

        String nomJ2 = nom2.getText();
        Joueur J2 = new Joueur(nomJ2);
        ListeJoueurs[1] = J2;

        nomJoueur1.setText(nomJ1);
        nomJoueur2.setText(nomJ2);

        ListeJoueurs[0].affecterCouleur("rouge");
        ListeJoueurs[1].affecterCouleur("jaune");

        Jeton jeton1 = new Jeton(ListeJoueurs[0].Couleur);
        ListeJoueurs[0].ajouterJeton(jeton1);
        Jeton jeton2 = new Jeton(ListeJoueurs[1].Couleur);
        ListeJoueurs[1].ajouterJeton(jeton2);

        couleurJoueur1.setText(J1.Couleur);
        couleurJoueur2.setText(J2.Couleur);

        nbdesintJoueur1.setText(J1.nombreDesintegrateurs + "");
        nbdesintJoueur2.setText(J2.nombreDesintegrateurs + "");

        joueurCourant = ListeJoueurs[0];
        joueur.setText(joueurCourant.Nom);

        for (int i = 1; i <= 3; i++) {
            int ligne;
            int colonne;

            ligne = (int) (Math.random() * 6);
            colonne = (int) (Math.random() * 7);
            boolean a = grilleDeJeu.CellulesJeu[ligne][colonne].placerTrouNoir();

            while (a == false) {
                a = grilleDeJeu.CellulesJeu[ligne][colonne].placerTrouNoir();
                ligne = (int) (Math.random() * 5);
                colonne = (int) (Math.random() * 6);
            }
        }
        for (int i = 1; i <= 2; i++) {
            int ligne;
            int colonne;

            ligne = (int) (Math.random() * 6);
            colonne = (int) (Math.random() * 7);
            boolean a = grilleDeJeu.CellulesJeu[ligne][colonne].placerTrouNoir();
            boolean b = grilleDeJeu.CellulesJeu[ligne][colonne].placerDesintegrateur();

            while (a == false || b == false) {
                a = grilleDeJeu.CellulesJeu[ligne][colonne].placerTrouNoir();
                b = grilleDeJeu.CellulesJeu[ligne][colonne].placerDesintegrateur();
                ligne = (int) (Math.random() * 5);
                colonne = (int) (Math.random() * 6);
            }
        }
        for (int i = 1; i <= 3; i++) {
            int ligne;
            int colonne;

            ligne = (int) (Math.random() * 6);
            colonne = (int) (Math.random() * 7);
            boolean b = grilleDeJeu.CellulesJeu[ligne][colonne].placerDesintegrateur();

            while (b == false || grilleDeJeu.CellulesJeu[ligne][colonne].presenceTrouNoir() == true) {
                b = grilleDeJeu.CellulesJeu[ligne][colonne].placerDesintegrateur();
                ligne = (int) (Math.random() * 5);
                colonne = (int) (Math.random() * 6);
            }
        }

    }

    public void attribueCouleursAuxJoueurs() {
        ListeJoueurs[0].affecterCouleur("jaune");
        System.out.println(ListeJoueurs[0].Nom + " tu as la couleur jaune.");
        ListeJoueurs[1].affecterCouleur("rouge");
        System.out.println(ListeJoueurs[1].Nom + " tu as la couleur rouge.");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanneauGrille;
    private javax.swing.JPanel PanneauInfoJeu;
    private javax.swing.JPanel PanneauInfoJoueur;
    private javax.swing.JPanel PanneauInfoPartie;
    private javax.swing.JButton col0;
    private javax.swing.JButton col1;
    private javax.swing.JButton col2;
    private javax.swing.JButton col3;
    private javax.swing.JButton col4;
    private javax.swing.JButton col5;
    private javax.swing.JButton col6;
    private javax.swing.JLabel couleurJoueur1;
    private javax.swing.JLabel couleurJoueur2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel joueur;
    private javax.swing.JTextArea message;
    private javax.swing.JLabel nbdesintJoueur1;
    private javax.swing.JLabel nbdesintJoueur2;
    private javax.swing.JTextField nom1;
    private javax.swing.JTextField nom2;
    private javax.swing.JLabel nomJoueur1;
    private javax.swing.JLabel nomJoueur2;
    private javax.swing.JButton start;
    // End of variables declaration//GEN-END:variables
}
